In [1]:
import pandas as pd

### Text to dates
- CSV dates arrive as text (`str`/`object`). Check `df.info()`.
- `df["d"] = pd.to_datetime(df["d"])` makes real dates (`datetime64`). Save it back.
- Real dates can be compared, sorted, `min()`/`max()`, and filtered: `df[df["d"] > "2026-10-01"]`.
- Standard text is year-month-day (`2026-10-05`). For other styles give `format`: `format="%d/%m/%Y"` (%d day, %m month, %Y 4-digit year, %y 2-digit, %b Oct, %B October, %H:%M time).
- Without `format`, `10/05/2026` is read month first (10 Oct). Day-first data needs `format="%d/%m/%Y"`.
- `errors="coerce"` turns bad dates into `NaT` (the date NaN). `isna()`, `dropna()`, `fillna()` work on it.
- Without `coerce`, one bad entry gives ValueError.
- A date from columns: `pd.to_datetime(df[["year","month","day"]])` (column names must be exactly year, month, day).
- A date with no time shows `00:00:00`.
- Watch out: forgetting the conversion (`.dt` then gives AttributeError); wrong `format` gives ValueError or wrong dates.

In [2]:
t = pd.DataFrame({"trip":   [1, 2, 3, 4],
                  "start":  ["2026-10-01", "2026-10-05", "2026-09-28", "2026-10-12"],
                  "amount": [500, 300, 450, 800]})
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   trip    4 non-null      int64
 1   start   4 non-null      object
 2   amount  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [4]:
t["start"] = pd.to_datetime(t["start"])
t.info()
print(t)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   trip    4 non-null      int64
 1   start   4 non-null      datetime64[ns]
 2   amount  4 non-null      int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 228.0 bytes
   trip      start  amount
0     1 2026-10-01     500
1     2 2026-10-05     300
2     3 2026-09-28     450
3     4 2026-10-12     800

In [8]:
print(t["start"].min())
print(t["start"].max())
print(t["start"].sort_values())

2026-09-28 00:00:00
2026-10-12 00:00:00
2   2026-09-28
0   2026-10-01
1   2026-10-05
3   2026-10-12
Name: start, dtype: datetime64[ns]

In [10]:
pd.to_datetime("15/10/2026",format="%d/%m/%Y")

Timestamp('2026-10-15 00:00:00')

In [12]:
pd.to_datetime("15/10/26",format="%d/%m/%y")

Timestamp('2026-10-15 00:00:00')

In [13]:
import pandas as pd

t = pd.DataFrame({"trip":   [1, 2, 3, 4],
                  "start":  ["2026-10-01", "2026-10-05", "2026-09-28", "2026-10-12"],
                  "amount": [500, 300, 450, 800]})
t.info()                                   # start is text (str / object)

t["start"] = pd.to_datetime(t["start"])    # text -> real dates
t.info()                                   # start is datetime64
print(t)

print(t["start"].min())                    # earliest date
print(t["start"].max())                    # latest date
print(t.sort_values("start"))              # sorted by date
print(t[t["start"] > "2026-10-01"])        # filter by date (compare with plain text)

# other date styles
print(pd.to_datetime("15/10/2026", format="%d/%m/%Y"))          # 2026-10-15
print(pd.to_datetime("10/05/2026"))                             # read month first: 2026-10-05
print(pd.to_datetime("10/05/2026", format="%d/%m/%Y"))          # day first: 2026-05-10
s = pd.Series(["15/10/2026", "01/09/2026", "31/12/2025"])
print(pd.to_datetime(s, format="%d/%m/%Y"))
print(pd.to_datetime("15 Oct 2026"), pd.to_datetime("October 15, 2026"))

# bad dates
bad = pd.Series(["2026-10-01", "hello", "2026-10-03"])
print(pd.to_datetime(bad, errors="coerce"))     # hello -> NaT

# a date from separate columns
d = pd.DataFrame({"day": [15, 16], "month": [10, 10], "year": [2026, 2026]})
print(pd.to_datetime(d))

# fail on purpose (remove the # to try one at a time)
# pd.to_datetime(bad)                           # ValueError: "hello" does not match the format
# pd.Series(["2026-10-01"]).dt.year             # AttributeError: .dt needs real dates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   trip    4 non-null      int64
 1   start   4 non-null      object
 2   amount  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   trip    4 non-null      int64
 1   start   4 non-null      datetime64[ns]
 2   amount  4 non-null      int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 228.0 bytes
   trip      start  amount
0     1 2026-10-01     500
1     2 2026-10-05     300
2     3 2026-09-28     450
3     4 2026-10-12     800
2026-09-28 00:00:00
2026-10-12 00:00:00
   trip      start  amount
2     3 2026-09-28     450
0     1 2026-10-01     500
1     2 2026-10-05     300
3     4 2026-10-12     800
   trip      start  amount
1     2 2026-10-05     300
3     4 2026-10-12     800
2026-10-15 00:00:00
2026-10-05 00:00:00
2026-05-10 00:00:00
0   2026-10-15
1   2026-09-01
2   2025-12-31
dtype: datetime64[ns]
2026-10-15 00:00:00 2026-10-15 00:00:00
0   2026-10-01
1          NaT
2   2026-10-03
dtype: datetime64[ns]
0   2026-10-15
1   2026-10-16
dtype: datetime64[ns]

### Parts of a date (.dt)
- Needs real dates (`pd.to_datetime` first), else AttributeError.
- No brackets: `.dt.year`, `.month`, `.day`, `.hour`, `.minute`, `.dayofweek` (Monday = 0 ... Sunday = 6), `.quarter`, `.dayofyear`.
- With brackets: `.dt.day_name()`, `.dt.month_name()`.
- Save pieces as columns (features for ML): `df["month"] = df["d"].dt.month`.
- Weekend: `df["d"].dt.dayofweek >= 5`.
- Filter by a piece: `df[df["d"].dt.month == 10]`.
- Filter by a range: `df[(df["d"] >= "2026-10-01") & (df["d"] < "2026-11-01")]`.
- `between(a, b)` includes both ends; a text date means midnight at the start of that day.
- Group by a piece: `df.groupby(df["d"].dt.month)["x"].sum()`. Month names sort A to Z, so use the number for order.
- Back to text: `df["d"].dt.strftime("%d-%m-%Y")`; `.dt.normalize()` sets the time to 00:00.
- Watch out: `.dt.month()` with brackets is a TypeError; `.dt` on a text column is an AttributeError.

In [14]:
import pandas as pd

t = pd.DataFrame({"trip":   [1, 2, 3, 4, 5, 6],
                  "start":  ["2026-10-01 09:30", "2026-10-05 18:45", "2026-09-28 07:10",
                             "2026-10-12 14:00", "2026-09-13 22:15", "2026-11-02 11:20"],
                  "amount": [500, 300, 450, 800, 250, 600]})
t["start"] = pd.to_datetime(t["start"])
print(t)

# step 1: pieces of a date
print(t["start"].dt.year.tolist())
print(t["start"].dt.month.tolist())
print(t["start"].dt.day.tolist())
print(t["start"].dt.hour.tolist())
print(t["start"].dt.minute.tolist())
print(t["start"].dt.day_name().tolist())
print(t["start"].dt.month_name().tolist())
print(t["start"].dt.dayofweek.tolist())     # Monday = 0 ... Sunday = 6
print(t["start"].dt.quarter.tolist())

# step 2: save pieces as columns
t["year"] = t["start"].dt.year
t["month"] = t["start"].dt.month
t["weekday"] = t["start"].dt.day_name()
t["is_weekend"] = t["start"].dt.dayofweek >= 5
print(t)

# step 3: filter
print(t[t["start"].dt.month == 10])                                       # October trips
print(t[t["is_weekend"]])                                                 # weekend trips
print(t[t["start"].dt.hour >= 12])                                        # afternoon and evening
print(t[(t["start"] >= "2026-10-01") & (t["start"] < "2026-11-01")])      # whole of October
print(t[t["start"].between("2026-09-20", "2026-10-05")])                  # inclusive range

# step 4: group by a piece
print(t.groupby("month")["amount"].sum())
print(t.groupby(t["start"].dt.month_name())["amount"].sum())
print(t.groupby("weekday")["amount"].count())
print(t["start"].dt.month.value_counts().sort_index())

# step 5: back to text
print(t["start"].dt.strftime("%d-%m-%Y").tolist())
print(t["start"].dt.strftime("%b %Y").tolist())
print(t["start"].dt.normalize().tolist())

# fail on purpose (remove the # to try one at a time)
# pd.Series(["2026-10-01"]).dt.year      # AttributeError: still text
# t["start"].dt.month()                  # TypeError: month has no brackets

   trip               start  amount
0     1 2026-10-01 09:30:00     500
1     2 2026-10-05 18:45:00     300
2     3 2026-09-28 07:10:00     450
3     4 2026-10-12 14:00:00     800
4     5 2026-09-13 22:15:00     250
5     6 2026-11-02 11:20:00     600
[2026, 2026, 2026, 2026, 2026, 2026]
[10, 10, 9, 10, 9, 11]
[1, 5, 28, 12, 13, 2]
[9, 18, 7, 14, 22, 11]
[30, 45, 10, 0, 15, 20]
['Thursday', 'Monday', 'Monday', 'Monday', 'Sunday', 'Monday']
['October', 'October', 'September', 'October', 'September', 'November']
[3, 0, 0, 0, 6, 0]
[4, 4, 3, 4, 3, 4]
   trip               start  amount  year  month   weekday  is_weekend
0     1 2026-10-01 09:30:00     500  2026     10  Thursday       False
1     2 2026-10-05 18:45:00     300  2026     10    Monday       False
2     3 2026-09-28 07:10:00     450  2026      9    Monday       False
3     4 2026-10-12 14:00:00     800  2026     10    Monday       False
4     5 2026-09-13 22:15:00     250  2026      9    Sunday        True
5     6 2026-11-02 11:20:00     600  2026     11    Monday       False
   trip               start  amount  year  month   weekday  is_weekend
0     1 2026-10-01 09:30:00     500  2026     10  Thursday       False
1     2 2026-10-05 18:45:00     300  2026     10    Monday       False
3     4 2026-10-12 14:00:00     800  2026     10    Monday       False
   trip               start  amount  year  month weekday  is_weekend
4     5 2026-09-13 22:15:00     250  2026      9  Sunday        True
   trip               start  amount  year  month weekday  is_weekend
1     2 2026-10-05 18:45:00     300  2026     10  Monday       False
3     4 2026-10-12 14:00:00     800  2026     10  Monday       False
4     5 2026-09-13 22:15:00     250  2026      9  Sunday        True
   trip               start  amount  year  month   weekday  is_weekend
0     1 2026-10-01 09:30:00     500  2026     10  Thursday       False
1     2 2026-10-05 18:45:00     300  2026     10    Monday       False
3     4 2026-10-12 14:00:00     800  2026     10    Monday       False
   trip               start  amount  year  month   weekday  is_weekend
0     1 2026-10-01 09:30:00     500  2026     10  Thursday       False
2     3 2026-09-28 07:10:00     450  2026      9    Monday       False
month
9      700
10    1600
11     600
Name: amount, dtype: int64
start
November      600
October      1600
September     700
Name: amount, dtype: int64
weekday
Monday      4
Sunday      1
Thursday    1
Name: amount, dtype: int64
start
9     2
10    3
11    1
Name: count, dtype: int64
['01-10-2026', '05-10-2026', '28-09-2026', '12-10-2026', '13-09-2026', '02-11-2026']
['Oct 2026', 'Oct 2026', 'Sep 2026', 'Oct 2026', 'Sep 2026', 'Nov 2026']
[Timestamp('2026-10-01 00:00:00'), Timestamp('2026-10-05 00:00:00'), Timestamp('2026-09-28 00:00:00'), Timestamp('2026-10-12 00:00:00'), Timestamp('2026-09-13 00:00:00'), Timestamp('2026-11-02 00:00:00')]

In [15]:
t = pd.DataFrame({"trip":   [1, 2, 3, 4, 5, 6],
                  "start":  ["2026-10-01 09:30", "2026-10-05 18:45", "2026-09-28 07:10",
                             "2026-10-12 14:00", "2026-09-13 22:15", "2026-11-02 11:20"],
                  "amount": [500, 300, 450, 800, 250, 600]})

t["start"] = pd.to_datetime(t["start"])
print(t)

   trip               start  amount
0     1 2026-10-01 09:30:00     500
1     2 2026-10-05 18:45:00     300
2     3 2026-09-28 07:10:00     450
3     4 2026-10-12 14:00:00     800
4     5 2026-09-13 22:15:00     250
5     6 2026-11-02 11:20:00     600

In [19]:
print(list(t["start"].dt.year))
print(list(t["start"].dt.day))
print(list(t["start"].dt.day_name()))

[2026, 2026, 2026, 2026, 2026, 2026]
[1, 5, 28, 12, 13, 2]
['Thursday', 'Monday', 'Monday', 'Monday', 'Sunday', 'Monday']

In [21]:
t[(t["start"] >= "2026-10-01") & (t["start"] < "2026-11-01")]     # all of October (trips 1, 2, 4)

   trip               start  amount
0     1 2026-10-01 09:30:00     500
1     2 2026-10-05 18:45:00     300
3     4 2026-10-12 14:00:00     800

In [22]:
t[t["start"].between("2026-09-20", "2026-10-05")]     # trips 1 and 3

   trip               start  amount
0     1 2026-10-01 09:30:00     500
2     3 2026-09-28 07:10:00     450

In [24]:
o = pd.DataFrame({"order_id":  [1, 2, 3, 4, 5],
                  "ordered":   ["2026-10-01", "2026-10-03", "2026-09-25", "2026-10-10", "2026-09-30"],
                  "delivered": ["2026-10-04", "2026-10-10", "2026-09-27", None, "2026-10-02"],
                  "amount":    [500, 300, 450, 800, 250]})
o["ordered"] = pd.to_datetime(o["ordered"])
o["delivered"] = pd.to_datetime(o["delivered"])      # None becomes NaT (a missing date)
print(o)

   order_id    ordered  delivered  amount
0         1 2026-10-01 2026-10-04     500
1         2 2026-10-03 2026-10-10     300
2         3 2026-09-25 2026-09-27     450
3         4 2026-10-10        NaT     800
4         5 2026-09-30 2026-10-02     250

In [26]:
gap = o["delivered"] - o["ordered"]
print(gap)
print(gap.dt.days)

0   3 days
1   7 days
2   2 days
3      NaT
4   2 days
dtype: timedelta64[ns]
0    3.0
1    7.0
2    2.0
3    NaN
4    2.0
dtype: float64

In [28]:
o["days_taken"] = (o["delivered"] - o["ordered"]).dt.days
print(o)

   order_id    ordered  delivered  amount  days_taken
0         1 2026-10-01 2026-10-04     500         3.0
1         2 2026-10-03 2026-10-10     300         7.0
2         3 2026-09-25 2026-09-27     450         2.0
3         4 2026-10-10        NaT     800         NaN
4         5 2026-09-30 2026-10-02     250         2.0

In [29]:
o["days_taken"].mean()            # 3.5  -> NaN is skipped
o["days_taken"].max()             # 7.0
o[o["days_taken"] > 3]            # slow deliveries: order 2

   order_id    ordered  delivered  amount  days_taken
1         2 2026-10-03 2026-10-10     300         7.0

In [30]:
o["days_taken"] = (o["delivered"] - o["ordered"]).dt.days

In [31]:
o["due"] = o["ordered"] + pd.Timedelta(days=7)
print(o["due"])

0   2026-10-08
1   2026-10-10
2   2026-10-02
3   2026-10-17
4   2026-10-07
Name: due, dtype: datetime64[ns]

In [32]:
print(o.groupby(o["ordered"].dt.to_period("M"))["amount"].sum())

ordered
2026-09     700
2026-10    1600
Freq: M, Name: amount, dtype: int64