In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\balar.chetan\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\balar.chetan\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\balar.chetan\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\balar.chetan\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\balar.chetan\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\balar.chetan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd        # open the pandas toolbox
pd.__version__             # show the installed version

'2.2.2'

### Key points — What pandas is
- pandas lets you work with tables using code.
- A row is one record; a column is one kind of information.
- A DataFrame is the whole table; a Series is one column.
- Start every notebook with `import pandas as pd`.

### Block 2 — Reading a CSV file
- CSV (Comma-Separated Values) is a table stored as plain text.
- The first line is the header: the column names.
- Every other line is one row; commas separate the columns.
- `pd.read_csv(path)` reads a CSV file and returns a DataFrame.
- Store the result in a variable (usually `df`) to use it later.
- A variable alone on the last line of a cell is shown as a neat table (notebooks only).
- `print(df)` shows the table as plain text and works on any line and in .py files.
- After editing a CSV file, run `read_csv` again; the DataFrame does not update by itself.

In [ ]:
df = pd.read_csv("students.csv") # read the CSV file into a DataFramdf
df 

#df          # not the last line, so Jupyter shows nothing for this
#print(df)   # print always shows, on any line

    name    city  marks
0   Asha  Indore     82
1  Vivek    Pune     91
2   Ravi   Delhi     67

Practice (Block 2: Reading a CSV)

Q1. In VS Code, create fruits.csv next to your notebook with the columns fruit, color, price and 4 fruits of your choice. Read it into a variable called fruits and display it. Before running, predict how many rows and columns you'll see.

Q2. Find the bug. Run this, read the error message, and fix it:

python
df = pd.read_csv(students.csv)

Q3. Add the line Meena,Indore,75 to the bottom of students.csv and save. Display the students table without running read_csv again. Is Meena there? Now run read_csv again. What changed, and why?

In [15]:
fruits = pd.read_csv("fruits.csv")
print(fruits)
fruits

        Fruit   Color  Price
0       Apple     Red     180
1  Strawberry     Red     200
2      Banana  Yellow      50
3   Pineapple  Yellow     110

        Fruit   Color  Price
0       Apple     Red     180
1  Strawberry     Red     200
2      Banana  Yellow      50
3   Pineapple  Yellow     110

In [17]:
#df = pd.read_csv(students.csv)       # buggy: no quotes around the file name
df = pd.read_csv("students.csv")     # fixed: quotes make the file name a piece of text
df

    name    city  marks
0   Asha  Indore     82
1  Vivek    Pune     91
2   Ravi   Delhi     67
3  Meena  Indore     75

In [18]:
df = pd.read_csv("students.csv")   # step 1: take a copy of the file (3 students)
df

    name    city  marks
0   Asha  Indore     82
1  Vivek    Pune     91
2   Ravi   Delhi     67
3  Meena  Indore     75

In [19]:
df = pd.read_csv("students.csv")   # step 1: take a copy of the file (3 students)
df

     name    city  marks
0    Asha  Indore     82
1   Vivek    Pune     91
2    Ravi   Delhi     67
3   Meena  Indore     75
4  Vinita  Indore     95

### Block 3 — Reading a file from another folder
- A path is the address of a file.
- A relative path starts from the folder the notebook is in.
- `..` means go up one folder; `/` means go into a folder.
- FileNotFoundError means the path is wrong or the file is not there.
- Datasets stay out of git: list their folders in `.gitignore` and note the download link in the README.

In [8]:
df = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_public.csv")   # go up one folder, then down to the survey file
df                                                                              # show the table                                                                              # show the table

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

Practice (Block 3: Paths)

Guess first, then code.

Q1. Write the path from notebooks/ to a file at data/processed/clean.csv. Just write the text; the file doesn't exist yet.

Q2. Imagine your notebook were saved directly in the pandas/ folder, not inside notebooks/. What would the path to the survey file be? (Hint: do you still need to go up?)

Q3. Find the bug. Run this from your notebook, read the error, and fix it:

python
df = pd.read_csv("data/raw/stackoverflow_2019/survey_results_public.csv")

Also explain why it fails.

Q4. Copy students.csv into data/raw/. Read it from your notebook into a variable called students using the right path, and display it.

In [24]:
# ../data/processed/clean.csv
# data/processed/clean.csv
# df = pd.read_csv("data/raw/stackoverflow_2019/survey_results_public.csv")
# we are running inside notebooks folder so we need to go one folder up and then we need to run df = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_public.csv")
students = pd.read_csv("../data/raw/students.csv")   # go up from notebooks/, then into data/raw/ to find the file
students                                              # show the table

     name    city  marks
0    Asha  Indore     82
1   Vivek    Pune     91
2    Ravi   Delhi     67
3   Meena  Indore     75
4  Vinita  Indore     95

In [23]:
import os                       # Python's toolbox for working with files and folders
os.listdir("../data/raw")       # list everything inside data/raw

['stackoverflow_2019']

### Block 4 — The schema file
- Survey columns have short names; the schema file explains each one.
- The schema has one row per survey column: the column name and the full question.
- Load it like any CSV with `pd.read_csv`.
- Keep the schema loaded while exploring, to look up unclear columns.

In [9]:
schema_df = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_schema.csv")   # read the file that explains each column
schema_df                                                                             # show it

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

Practice (Block 4: Schema)

Guess first, then code.

Q1. Load the schema into schema_df and display it. How many rows does it have? Why does that number match the number of columns in the survey df?

Q2. Predict without code: if a survey had 100 columns, how many rows would its schema file have?

Q3. Look at the first few rows of schema_df. What does the column MainBranch mean? And OpenSourcer?
(If the question text is cut off with ..., that's normal. Block 7 shows how to see the full text. Write down what you can see.)

Q4. Make your own mini schema. In VS Code, create fruits_schema.csv next to your notebook with the columns Column and QuestionText, and one row each explaining Fruit, Color, and Price (write the explanations yourself). Read it into fruits_schema and display it. Predict rows × columns first.

In [ ]:
schema_df = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_schema.csv")   # read the file that explains each column
schema_df     

# 85 rows 
#                                                                         # show it

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [27]:
schema = pd.read_csv("fruits_schema.csv")
schema

  Column    QuestionText
0  Fruit      fruit name
1  Color  color of fruit
2  Price    price per kg

### Block 5 — shape and info()
- `df.shape` gives the size of the table as (rows, columns).
- `df.info()` prints one line per column: name, non-null count and data type, plus the total rows and memory used.
- Non-null count = how many values are filled in; fewer than the number of rows means the column has missing values.
- Common dtypes: int64 = whole numbers, float64 = decimals, object = text.
- Attributes (like `shape`) have no brackets; methods (like `info()`) have brackets because they perform an action.
- Jupyter shows only the value of the last line in a cell; use `print()` to show values from earlier lines.
- `info()` prints by itself, so its report shows from any line.
- Run `shape` and `info()` first on every new dataset.

In [33]:
df = pd.read_csv("students.csv")
df.shape
print(df.shape)
df.info()                           # one line per column: name, filled count, data type
#Rule to remember: to see several things from one cell, use print() for everything except the last line.

(5, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   city    5 non-null      object
 2   marks   5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

Q1. Predict fruits.shape, then check it.

Q2. Load the survey into a variable called survey and run survey.shape. How many people answered, and how many questions are there?

Q3. Find the bug. Run df.shape(), read the last line of the error, and fix it. Why does it fail?

Q4. Run survey.info(). Do all columns show 88883 non-null? What does it mean when a column shows fewer?

Q5. Predict without code: a CSV has 1 header line and 50 more lines, and each line has 7 commas. What is its shape?

In [36]:
fruits = pd.read_csv("fruits.csv")   # load the fruits table
fruits.shape                          # size as (rows, columns)

(4, 3)

In [37]:
survey = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_public.csv")   # load the survey
survey.shape                                                                         # size as (rows, columns)

(88883, 85)

In [38]:
#df.shape()    # buggy: brackets after shape
df.shape      # correct: shape is a fact, not an action

(5, 3)

In [39]:
survey.info()   # one line per column: name, filled count, data type (no print needed)
#(50, 8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              88883 non-null  int64
 1   MainBranch              88331 non-null  object
 2   Hobbyist                88883 non-null  object
 3   OpenSourcer             88883 non-null  object
 4   OpenSource              86842 non-null  object
 5   Employment              87181 non-null  object
 6   Country                 88751 non-null  object
 7   Student                 87014 non-null  object
 8   EdLevel                 86390 non-null  object
 9   UndergradMajor          75614 non-null  object
 10  EduOther                84260 non-null  object
 11  OrgSize                 71791 non-null  object
 12  DevType                 81335 non-null  object
 13  YearsCode               87938 non-null  object
 14  Age1stCode              87634 non-null  object
 15  YearsCodePro            74331 non-null  object
 16  CareerSat               72847 non-null  object
 17  JobSat                  70988 non-null  object
 18  MgrIdiot                61159 non-null  object
 19  MgrMoney                61157 non-null  object
 20  MgrWant                 61232 non-null  object
 21  JobSeek                 80555 non-null  object
 22  LastHireDate            79854 non-null  object
 23  LastInt                 67155 non-null  object
 24  FizzBuzz                71344 non-null  object
 25  JobFactors              79371 non-null  object
 26  ResumeUpdate            77877 non-null  object
 27  CurrencySymbol          71392 non-null  object
 28  CurrencyDesc            71392 non-null  object
 29  CompTotal               55945 non-null  float64
 30  CompFreq                63268 non-null  object
 31  ConvertedComp           55823 non-null  float64
 32  WorkWeekHrs             64503 non-null  float64
 33  WorkPlan                68914 non-null  object
 34  WorkChallenge           68141 non-null  object
 35  WorkRemote              70284 non-null  object
 36  WorkLoc                 70055 non-null  object
 37  ImpSyn                  71779 non-null  object
 38  CodeRev                 70390 non-null  object
 39  CodeRevHrs              49790 non-null  float64
 40  UnitTests               62668 non-null  object
 41  PurchaseHow             61108 non-null  object
 42  PurchaseWhat            62029 non-null  object
 43  LanguageWorkedWith      87569 non-null  object
 44  LanguageDesireNextYear  84088 non-null  object
 45  DatabaseWorkedWith      76026 non-null  object
 46  DatabaseDesireNextYear  69147 non-null  object
 47  PlatformWorkedWith      80714 non-null  object
 48  PlatformDesireNextYear  77443 non-null  object
 49  WebFrameWorkedWith      65022 non-null  object
 50  WebFrameDesireNextYear  62944 non-null  object
 51  MiscTechWorkedWith      59586 non-null  object
 52  MiscTechDesireNextYear  64511 non-null  object
 53  DevEnviron              87317 non-null  object
 54  OpSys                   87851 non-null  object
 55  Containers              85366 non-null  object
 56  BlockchainOrg           48175 non-null  object
 57  BlockchainIs            60165 non-null  object
 58  BetterLife              86269 non-null  object
 59  ITperson                87141 non-null  object
 60  OffOn                   86663 non-null  object
 61  SocialMedia             84437 non-null  object
 62  Extraversion            87305 non-null  object
 63  ScreenName              80486 non-null  object
 64  SOVisit1st              83877 non-null  object
 65  SOVisitFreq             88263 non-null  object
 66  SOVisitTo               88086 non-null  object
 67  SOFindAnswer            87816 non-null  object
 68  SOTimeSaved             86344 non-null  object
 69  SOHowMuchTime           68378 non-null  object
 70  SOAccount               87828 non-null  object
 71  SOPartFreq              74692 non-null  object
 72  SOJobs                  88066 non-null  object
 73  EntTeams                87841 non-null  object
 74  SOComm                  88131 non-null  object
 75  WelcomeChange           85855 non-null  object
 76  SONewContent            69560 non-null  object
 77  Age                     79210 non-null  float64
 78  Gender                  85406 non-null  object
 79  Trans                   83607 non-null  object
 80  Sexuality               76147 non-null  object
 81  Ethnicity               76668 non-null  object
 82  Dependents              83059 non-null  object
 83  SurveyLength            86984 non-null  object
 84  SurveyEase              87081 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [40]:
print(survey.shape)            # rows and columns of the survey
print(list(survey.columns))    # every column name, as a list

(88883, 85)
['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith', 'DatabaseDesireNextYear', 'PlatformWorkedWith', 'PlatformDesireNextYear', 'WebFrameWorkedWith', 'WebFrameDesireNextYear', 'MiscTechWorkedWith', 'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers', 'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn', 'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st', 'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved', 'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams', 'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans', 'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase']

### Block 6 — head() and tail()
- `df.head(n)` shows the first n rows; `df.tail(n)` shows the last n rows.
- With no number, both show 5 rows.
- Row labels keep their original numbers; they are not renumbered.
- Rows are counted from 0, so the last row's label is (number of rows - 1).
- They return a small copy for viewing; the original DataFrame is unchanged.
- Use them to see real values in a large table without printing everything.

Practice (Block 6)

Guess first, then code. They get harder as you go.

Q1. Show the first 3 rows of fruits.

Q2. Show the last 10 rows of survey. What is the row number of the very last row? Why isn't it 88883?

Q3. Predict: what does survey.head() show if you don't give a number?

Q4. Predict: students has 4 rows. What happens with df.head(10)? An error, or something else? Then check.

Q5. Find the bug. Run survey.head (no brackets). What appears? Why is it strange?

Q6. Combine with Block 5: predict survey.head(7).shape, then check.

In [45]:
fruits = pd.read_csv("fruits.csv")  # read the CSV file into a DataFrame
print(fruits.head(3))                        # show the first 3 rows of the table
#ques 5 in another version
print(fruits.head(10))                       # show the first 10 rows of the table

survey = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_public.csv")   # load the survey
print(survey.tail(10))   # show the last 10 rows of the survey
# row counting starts from 0
print(survey.head())

print(survey.head())

survey.head     # no brackets: refers to the action, but doesn't run it
survey.head(7).shape

        Fruit   Color  Price
0       Apple     Red     180
1  Strawberry     Red     200
2      Banana  Yellow      50
        Fruit   Color  Price
0       Apple     Red     180
1  Strawberry     Red     200
2      Banana  Yellow      50
3   Pineapple  Yellow     110
       Respondent MainBranch Hobbyist  \
88873       88062        NaN       No
88874       88076        NaN       No
88875       88182        NaN      Yes
88876       88212        NaN       No
88877       88282        NaN      Yes
88878       88377        NaN      Yes
88879       88601        NaN       No
88880       88802        NaN       No
88881       88816        NaN       No
88882       88863        NaN      Yes

                                             OpenSourcer  \
88873                                              Never
88874                                              Never
88875                         Once a month or more often
88876                            Less than once per year
88877                         Once a month or more often
88878  Less than once a month but more than once per ...
88879                                              Never
88880                                              Never
88881                                              Never
88882                            Less than once per year

                                              OpenSource  \
88873  OSS is, on average, of LOWER quality than prop...
88874  OSS is, on average, of HIGHER quality than pro...
88875  OSS is, on average, of HIGHER quality than pro...
88876  OSS is, on average, of HIGHER quality than pro...
88877  The quality of OSS and closed source software ...
88878  The quality of OSS and closed source software ...
88879  The quality of OSS and closed source software ...
88880                                                NaN
88881  OSS is, on average, of HIGHER quality than pro...
88882  OSS is, on average, of HIGHER quality than pro...

                                              Employment        Country  \
88873                                                NaN            NaN
88874                                 Employed full-time            NaN
88875                                 Employed part-time       Pakistan
88876                                 Employed full-time          Spain
88877                 Not employed, but looking for work  United States
88878             Not employed, and not looking for work         Canada
88879                                                NaN            NaN
88880                                 Employed full-time            NaN
88881  Independent contractor, freelancer, or self-em...            NaN
88882             Not employed, and not looking for work          Spain

              Student                                            EdLevel  \
88873             NaN                                                NaN
88874             NaN                                                NaN
88875             NaN  Secondary school (e.g. American high school, G...
88876              No  Secondary school (e.g. American high school, G...
88877              No  Some college/university study without earning ...
88878              No                          Primary/elementary school
88879             NaN                                                NaN
88880             NaN                                                NaN
88881             NaN                                                NaN
88882  Yes, full-time                 Professional degree (JD, MD, etc.)

                                          UndergradMajor  ...  \
88873                                                NaN  ...
88874                                                NaN  ...
88875                                                NaN  ...
88876                                                NaN  ...
88877  Computer science, computer engineering, or sof...  ...
88878                                                NaN  ...
88879                                                NaN  ...
88880                                                NaN  ...
88881                                                NaN  ...
88882  Computer science, computer engineering, or sof...  ...

                                           WelcomeChange  \
88873                                                NaN
88874                                                NaN
88875  Not applicable - I did not use Stack Overflow ...
88876                                                NaN
88877            Just as welcome now as I felt last year
88878                                                NaN
88879                                                NaN
88880                                                NaN
88881                                                NaN
88882           Somewhat less welcome now than last year

                                            SONewContent   Age Gender Trans  \
88873                                                NaN   NaN    NaN   NaN
88874                                                NaN   NaN    NaN   NaN
88875       Courses on technologies you're interested in   NaN    Man    No
88876  Tech articles written by other developers;Indu...  40.0    Man    No
88877                                                NaN   NaN    Man    No
88878  Tech articles written by other developers;Tech...   NaN    Man    No
88879                                                NaN   NaN    NaN   NaN
88880                                                NaN   NaN    NaN   NaN
88881                                                NaN   NaN    NaN   NaN
88882  Tech articles written by other developers;Indu...  18.0    Man    No

                     Sexuality  \
88873                      NaN
88874                      NaN
88875  Straight / Heterosexual
88876  Straight / Heterosexual
88877  Straight / Heterosexual
88878                      NaN
88879                      NaN
88880                      NaN
88881                      NaN
88882  Straight / Heterosexual

                                               Ethnicity Dependents  \
88873                                                NaN        NaN
88874                                                NaN        NaN
88875                                                NaN        Yes
88876                       White or of European descent         No
88877                                                NaN         No
88878                                                NaN         No
88879                                                NaN        NaN
88880                                                NaN        NaN
88881                                                NaN        NaN
88882  Hispanic or Latino/Latina;White or of European...         No

                SurveyLength                  SurveyEase
88873                    NaN                         NaN
88874                    NaN                         NaN
88875              Too short  Neither easy nor difficult
88876  Appropriate in length                        Easy
88877              Too short  Neither easy nor difficult
88878  Appropriate in length                        Easy
88879                    NaN                         NaN
88880                    NaN                         NaN
88881                    NaN                         NaN
88882  Appropriate in length                        Easy

[10 rows x 85 columns]
   Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes
1           2             I am a student who is learning to code       No
2           3  I am not primarily a developer, but I write co...      Yes
3           4                     I am a developer by profession       No
4           5                     I am a developer by profession      Yes

                  OpenSourcer  \
0                       Never
1     Less than once per year
2                       Never
3                       Never
4  Once a month or more often

                                          OpenSource  \
0  The quality of OSS and closed source software ...
1  The quality of OSS and closed source software ...
2  The quality of OSS and closed source software ...
3  The quality of OSS and closed source software ...
4  OSS is, on average, of HIGHER quality than pro...

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom
1      Not employed, but looking for work  Bosnia and Herzegovina
2                      Employed full-time                Thailand
3                      Employed full-time           United States
4                      Employed full-time                 Ukraine

          Student                                            EdLevel  \
0              No                          Primary/elementary school
1  Yes, full-time  Secondary school (e.g. American high school, G...
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)

                                      UndergradMajor  ...  \
0                                                NaN  ...
1                                                NaN  ...
2                      Web development or web design  ...
3  Computer science, computer engineering, or sof...  ...
4  Computer science, computer engineering, or sof...  ...

                             WelcomeChange  \
0  Just as welcome now as I felt last year
1  Just as welcome now as I felt last year
2  Just as welcome now as I felt last year
3  Just as welcome now as I felt last year
4  Just as welcome now as I felt last year

                                        SONewContent   Age Gender Trans  \
0  Tech articles written by other developers;Indu...  14.0    Man    No
1  Tech articles written by other developers;Indu...  19.0    Man    No
2  Tech meetups or events in your area;Courses on...  28.0    Man    No
3  Tech articles written by other developers;Indu...  22.0    Man    No
4  Tech meetups or events in your area;Courses on...  30.0    Man    No

                 Sexuality                                 Ethnicity  \
0  Straight / Heterosexual                                       NaN
1  Straight / Heterosexual                                       NaN
2  Straight / Heterosexual                                       NaN
3  Straight / Heterosexual              White or of European descent
4  Straight / Heterosexual  White or of European descent;Multiracial

  Dependents           SurveyLength                  SurveyEase
0         No  Appropriate in length  Neither easy nor difficult
1         No  Appropriate in length  Neither easy nor difficult
2        Yes  Appropriate in length  Neither easy nor difficult
3         No  Appropriate in length                        Easy
4         No  Appropriate in length                        Easy

[5 rows x 85 columns]
   Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes
1           2             I am a student who is learning to code       No
2           3  I am not primarily a developer, but I write co...      Yes
3           4                     I am a developer by profession       No
4           5                     I am a developer by profession      Yes

                  OpenSourcer  \
0                       Never
1     Less than once per year
2                       Never
3                       Never
4  Once a month or more often

                                          OpenSource  \
0  The quality of OSS and closed source software ...
1  The quality of OSS and closed source software ...
2  The quality of OSS and closed source software ...
3  The quality of OSS and closed source software ...
4  OSS is, on average, of HIGHER quality than pro...

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom
1      Not employed, but looking for work  Bosnia and Herzegovina
2                      Employed full-time                Thailand
3                      Employed full-time           United States
4                      Employed full-time                 Ukraine

          Student                                            EdLevel  \
0              No                          Primary/elementary school
1  Yes, full-time  Secondary school (e.g. American high school, G...
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)

                                      UndergradMajor  ...  \
0                                                NaN  ...
1                                                NaN  ...
2                      Web development or web design  ...
3  Computer science, computer engineering, or sof...  ...
4  Computer science, computer engineering, or sof...  ...

                             WelcomeChange  \
0  Just as welcome now as I felt last year
1  Just as welcome now as I felt last year
2  Just as welcome now as I felt last year
3  Just as welcome now as I felt last year
4  Just as welcome now as I felt last year

                                        SONewContent   Age Gender Trans  \
0  Tech articles written by other developers;Indu...  14.0    Man    No
1  Tech articles written by other developers;Indu...  19.0    Man    No
2  Tech meetups or events in your area;Courses on...  28.0    Man    No
3  Tech articles written by other developers;Indu...  22.0    Man    No
4  Tech meetups or events in your area;Courses on...  30.0    Man    No

                 Sexuality                                 Ethnicity  \
0  Straight / Heterosexual                                       NaN
1  Straight / Heterosexual                                       NaN
2  Straight / Heterosexual                                       NaN
3  Straight / Heterosexual              White or of European descent
4  Straight / Heterosexual  White or of European descent;Multiracial

  Dependents           SurveyLength                  SurveyEase
0         No  Appropriate in length  Neither easy nor difficult
1         No  Appropriate in length  Neither easy nor difficult
2        Yes  Appropriate in length  Neither easy nor difficult
3         No  Appropriate in length                        Easy
4         No  Appropriate in length                        Easy

[5 rows x 85 columns]

(7, 85)

### Block 7 — Display options
- `pd.set_option(name, value)` changes how much pandas shows; the data itself never changes.
- Settings start with `pd.`, so they apply to every table in the notebook, not one table.
- `display.max_columns`: most columns shown before the middle is hidden with "..." (default 20). None = no limit.
- `display.max_rows`: most rows shown before the middle is hidden (default 60). Use a number, never None.
- `display.max_colwidth`: most characters shown per text cell (default 50). None = full text.
- The value is a limit: a table bigger than the limit is still cut with "...".
- `pd.reset_option(name)` puts one setting back to its default; restarting the kernel resets all settings.
- Put settings in a cell right after `import pandas as pd`.
- For very large tables, use head() and tail() instead of raising max_rows.

Q1. Undo the column setting with reset_option and display survey.head(). Is the ... back in the middle of the columns?

In [53]:
pd.reset_option("display.max_columns")   
survey.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Courses on technologies you're interested in,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",...,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

2: remove the column limit with None, display survey.head(), scroll to the Country column, and tell me the country in row 0.

In [55]:
pd.set_option("display.max_columns",None)   # show all columns, no matter how many
survey.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Courses on technologies you're interested in,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,"Financial performance or funding status of the company or organization;Specific department or team I'd be working on;Languages, frameworks, and other technologies I'd be working with","Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time or a flexible schedule",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company culture;Opportunities for professional development",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software","10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Developer, mobile",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Interview with people in senior / management roles",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working with;Flex time or a flexible schedule",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely","Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments (parenting, school work, hobbies, etc.)",A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

Q3: with full text switched on (display.max_colwidth set to None), display schema_df. What is the complete question for MainBranch? Copy it here.

In [56]:
pd.set_option("display.max_colwidth", None)   
schema_df

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order of survey response time)
1,MainBranch,"Which of the following options best describes you today? Here, by ""developer"" we mean ""someone who writes code."""
2,Hobbyist,Do you code as a hobby?
3,OpenSourcer,How often do you contribute to open source?
4,OpenSource,How do you feel about the quality of open source software (OSS)?
5,Employment,Which of the following best describes your current employment status?
6,Country,In which country do you currently reside?
7,Student,"Are you currently enrolled in a formal, degree-granting college or university program?"
8,EdLevel,Which of the following best describes the highest level of formal education that you’ve completed?
9,UndergradMajor,What was your main or most important field of study?
10,EduOther,Which of the following types of non-degree education have you used or participated in? Please select all that apply.
11,OrgSize,Approximately how many people are employed by the company or organization you work for?
12,DevType,Which of the following describe you? Please select all that apply.
13,YearsCode,"Including any education, how many years have you been coding?"
14,Age1stCode,"At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scratch project)"
15,YearsCodePro,How many years have you coded professionally (as a part of your work)?
16,CareerSat,"Overall, how satisfied are you with your career thus far?"
17,JobSat,"How satisfied are you with your current job? (If you work multiple jobs, answer for the one you spend the most hours on.)"
18,MgrIdiot,How confident are you that your manager knows what they’re doing?
19,MgrMoney,Do you believe that you need to be a manager to make more money?
20,MgrWant,Do you want to become a manager yourself in the future?
21,JobSeek,Which of the following best describes your current job-seeking status?
22,LastHireDate,When was the last time that you took a job with a new employer?
23,LastInt,"In your most recent successful job interview (resulting in a job offer), you were asked to... (check all that apply)"
24,FizzBuzz,Have you ever been asked to solve FizzBuzz in an interview?
25,JobFactors,"Imagine that you are deciding between two job offers with the same compensation, benefits, and location. Of the following factors, which 3 are MOST important to you?"
26,ResumeUpdate,"Think back to the last time you updated your resumé, CV, or an online profile on a job site. What is the PRIMARY reason that you did so?"
27,CurrencySymbol,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in."
28,CurrencyDesc,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in."
29,CompTotal,"What is your current total compensation (salary, bonuses, and perks, before taxes and deductions), in `CurrencySymbol`? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent weekly, monthly, or yearly salary. If you prefer not to answer, please leave the box empty."
30,CompFreq,"Is that compensation weekly, monthly, or yearly?"
31,ConvertedComp,"Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 working months and 50 working weeks."
32,WorkWeekHrs,"On average, how many hours per week do you work?"
33,WorkPlan,How structured or planned is your work?
34,WorkChallenge,"Of these options, what are your greatest challenges to productivity as a developer? Select up to 3:"
35,WorkRemote,How often do you work remotely?
36,WorkLoc,Where would you prefer to work?
37,ImpSyn,"For the specific work you do, and the years of experience you have, how do you rate your own level of competence?"
38,CodeRev,Do you review code as part of your work?
39,CodeRevHrs,"On average, how many hours per week do you spend on code review?"
40,UnitTests,Does your company regularly employ unit tests in the development of their products?
41,PurchaseHow,"How does your company make decisions about purchasing new technology (cloud, AI, IoT, databases)?"
42,PurchaseWhat,"What level of influence do you, personally, have over new technology purchases at your organization?"
43,LanguageWorkedWith,"Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)"
44,LanguageDesireNextYear,"Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)"
45,DatabaseWorkedWith,"Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)"
46,DatabaseDesireNextYear,"Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)"
47,PlatformWorkedWith,"Which of the following platforms have you done extensive development work for over the past year? (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)"
48,PlatformDesireNextYear,"Which of the following platforms have you done extensive development work for over the past year? (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)"
49,WebFrameWorkedWith,"Which of the following web frameworks have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)"
50,WebFrameDesireNextYear,"Which of the following web frameworks have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)"
51,MiscTechWorkedWith,"Which of the following other frameworks, libraries, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the technology and want to continue to do so, please check both boxes in that row.)"
52,MiscTechDesireNextYear,"Which of the following other frameworks, libraries, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the technology and want to continue to do so, please check both boxes in that row.)"
53,DevEnviron,Which development environment(s) do you use regularly? Please check all that apply.
54,OpSys,What is the primary operating system in which you work?
55,Containers,"How do you use containers (Docker, Open Container Initiative (OCI), etc.)?"
56,BlockchainOrg,How is your organization thinking about or implementing blockchain technology?
57,BlockchainIs,Blockchain / cryptocurrency technology is primarily:
58,BetterLife,Do you think people born today will have a better life than their parents?
59,ITperson,"Are you the ""IT support person"" for your family?"
60,OffOn,Have you tried turning it off and on again?
61,SocialMedia,What social media site do you use the most?
62,Extraversion,Do you prefer online chat or IRL conversations?
63,ScreenName,What do you call it?
64,SOVisit1st,"To the best of your memory, when did you first visit Stack Overflow?"
65,SOVisitFreq,How frequently would you say you visit Stack Overflow?
66,SOVisitTo,I visit Stack Overflow to... (check all that apply)
67,SOFindAnswer,"On average, how many times a week do you find (and use) an answer on Stack Overflow?"
68,SOTimeSaved,"Think back to the last time you solved a coding problem using Stack Overflow, as well as the last time you solved a problem using a different resource. Which was faster?"
69,SOHowMuchTime,"About how much time did you save? If you're not sure, please use your best estimate."
70,SOAccount,Do you have a Stack Overflow account?
71,SOPartFreq,"How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean ask, answer, vote for, or comment on questions."
72,SOJobs,Have you ever used or visited Stack Overflow Jobs?
73,EntTeams,Have you ever used Stack Overflow for Enterprise or Stack Overflow for Teams?
74,SOComm,Do you consider yourself a member of the Stack Overflow community?
75,WelcomeChange,"Compared to last year, how welcome do you feel on Stack Overflow?"
76,SONewContent,Would you like to see any of the following on Stack Overflow? Check all that apply.
77,Age,"What is your age (in years)? If you prefer not to answer, you may leave this question blank."
78,Gender,"Which of the following do you currently identify as? Please select all that apply. If you prefer not to answer, you may leave this question blank."
79,Trans,Do you identify as transgender?
80,Sexuality,"Which of the following do you currently identify as? Please select all that apply. If you prefer not to answer, you may leave this question blank."
81,Ethnicity,"Which of the following do you identify as? Please check all that apply. If you prefer not to answer, you may leave this question blank."
82,Dependents,"Do you have any dependents (e.g., children, elders, or others) that you care for?"
83,SurveyLength,How do you feel about the length of the survey this year?
84,SurveyEase,How easy or difficult was this survey to complete?

#Now Q4 (find the bug): run this, read the last line of the error, and fix it:


pd.set_option(display.max_columns, 85)

# pd.set_option("display.max_columns", 85)

Q5. After changing max_columns, does survey.shape change? Why or why not?

Q6. Why is pd.set_option("display.max_rows", None) followed by survey a bad idea, and what should you use instead?

A5. No change. It stays (88883, 85). Settings only change what's shown on screen; the data itself isn't touched, and shape counts the data.

A6.  Use head() or tail(). The reason: with no row limit, pandas would try to display all 88,883 rows, which makes the notebook very slow or freezes it.

### Block 8 — describe()
- `df.describe()` gives summary statistics for every number column.
- Text columns are skipped by default.
- count = how many values are filled in (missing values are not counted).
- mean = average; std = how spread out the values are.
- min and max = smallest and largest values.
- 25%, 50%, 75% = values a quarter, half and three quarters of the way up the sorted data; 50% is the middle value (median).
- Use it to see typical values and to spot strange ones, such as impossible minimums or maximums.

Q1. Run fruits.describe(). Which column appears, and why only that one?

In [ ]:
fruits.describe()
# because the table has only 1 column which contains numbers, the summary shows only that column. If there were more numeric columns, they would be summarized too.

           Price
count    4.000000
mean   135.000000
std     68.556546
min     50.000000
25%     95.000000
50%    145.000000
75%    185.000000
max    200.000000

Q2. Using that output:

What is the cheapest price, and which fruit is it?
What is the most expensive price, and which fruit is it?
What is the average? Check it by hand: add the 4 prices and divide by 4. Write out your working.

In [60]:
# 50
# 200
# 135

Q3. Run this:

python
survey.describe()     # summary numbers for every number column in the survey

Then answer:

How many columns appear, out of 85? Write their names.
Why so few?

6 columns appear: Respondent, CompTotal, ConvertedComp, WorkWeekHrs, CodeRevHrs, Age. Check that yours shows the same 6.

Why so few: most survey answers are text, like "Yes"/"No", country names, or lists of languages.

A surprise worth noticing: YearsCode (years of coding) sounds like a number column but is missing. Some people answered with text like "Less than 1 year" or "More than 50 years". One text answer makes pandas treat the whole column as text, so describe() skips it. Fixing columns like this is exactly what you'll do in Topic 9, and it's a very common MLP task.

Q4. In survey.describe(), look at the count row. Why is Respondent's count 88883, while ConvertedComp's count is smaller?

count = how many cells are filled. Empty (missing) cells aren't counted