# 02 — Series and DataFrames

In [1]:
import pandas as pd                           # open the pandas toolbox
pd.set_option("display.max_columns", None)    # show every column in every table

In [2]:
students = pd.read_csv("students.csv")                                            # load the students table
survey = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_public.csv")  # load the survey
print(students.shape, survey.shape)                                               # quick check both loaded

(5, 3) (88883, 85)

### Block 1 — Building a DataFrame from a dict
- A list holds values in order inside square brackets: [a, b, c].
- A dict holds key → value pairs inside curly brackets: {"key": value}.
- Look up a dict value by its key: d["key"].
- `pd.DataFrame(dict_of_lists)` builds a table: each key becomes a column name, each list fills that column.
- Item positions line up into rows: the first item of every list forms row 0.
- All lists must have the same length, otherwise pandas raises an error.
- DataFrame is written with capital D and F.
- Building tables from dicts is the quickest way to make small test data without a file.

Practice (Block 1)

Guess first, then code.

Q1. Make a list called cities with 4 city names and display it.

Q2. Make a dict called fruit with the keys name, color, price for one fruit. Then look up its price using the key.

Q3. Build a DataFrame called books from a dict with the columns title, author, pages for 3 books of your choice. Predict its shape first, then display the table and check the shape.

Q4. Find the bug. Run this, read the last line of the error, and fix it:

In [8]:
# Q1: a list
cities = ["Indore", "Bhopal", "Gwalior", "Jabalpur"]                       # a list of 4 city names
print("Q1:", cities)                                                        # show the list

# Q2: a dict and a key lookup
fruit = {"name": "apple", "color": "red", "price": 100}                    # a dict describing one fruit
print("Q2:", fruit["price"])                                                # look up the value under "price"

# Q3: DataFrame from a dict (prediction: (3, 3))
books_data = {                                                              # dict: column name → list of values
    "title":  ["Python for Data Analysis", "Python Crash Course", "Fluent Python"],
    "author": ["Wes McKinney", "Eric Matthes", "Luciano Ramalho"],
    "pages":  [330, 560, 770],
}
books = pd.DataFrame(books_data)                                            # turn the dict into a table
print("Q3:", books.shape)                                                   # check the shape
print(books)                                                                # show the table

# Q4: 
data = {"name": ["Asha", "Vivek", "Ravi"], "marks": [82, 91, 88]}          # both lists now have 3 values
print("Q4:")                                                                # label for the output
print(pd.DataFrame(data))                                                   # build and show the table

# Q5: 
print("Q5:")                                                                # label for the output
print(pd.DataFrame({"a": [1, 2]}))                                          # capital D and F

# Q6: prediction (5, 2): 5 values per list = 5 rows, 2 keys = 2 columns
check = pd.DataFrame({"x": [1, 2, 3, 4, 5], "y": [6, 7, 8, 9, 10]})       # a test table to confirm
print("Q6:", check.shape)                                                   # should print (5, 2)

Q1: ['Indore', 'Bhopal', 'Gwalior', 'Jabalpur']
Q2: 100
Q3: (3, 3)
                      title           author  pages
0  Python for Data Analysis     Wes McKinney    330
1       Python Crash Course     Eric Matthes    560
2             Fluent Python  Luciano Ramalho    770
Q4:
    name  marks
0   Asha     82
1  Vivek     91
2   Ravi     88
Q5:
   a
0  1
1  2
Q6: (5, 2)

### Block 2 — What a Series is
- A Series is a single column: values + row labels (index) + an optional name + one dtype.
- A DataFrame is several Series side by side that share the same row labels.
- `pd.Series(list, name="...")` builds a Series from a list.
- A Series is displayed without table borders, with a "Name: ..., dtype: ..." line at the bottom.
- `type(x)` shows whether x is a Series, a DataFrame, or something else.
- Series is written with a capital S.
- In ML, the target column you want to predict is usually a Series.

Q1. Take out the city column from students and display it. Is it a DataFrame or a Series?

In [12]:
students = pd.read_csv('students.csv')
print(students["city"])
print(type(students["city"]))  # should print <class 'pandas.core.series.Series'>

0    Indore
1      Pune
2     Delhi
3    Indore
4    Indore
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Q3. Make your own Series and display it:

In [ ]:
mark = pd.Series([23,65,87,98,99],name="marks")
print(mark)
mark.shape

#Why only one number: a Series is a single column, so it only has length, how many values it holds. It has no "number of columns" because it is one column. 
# A DataFrame needs two numbers (rows, columns); a Series needs only one.

0    23
1    65
2    87
3    98
4    99
Name: marks, dtype: int64

(5,)

In [17]:
pd.Series([1, 2, 3])

0    1
1    2
2    3
dtype: int64

In [21]:
mark.describe()

count     5.000000
mean     74.400000
std      31.824519
min      23.000000
25%      65.000000
50%      87.000000
75%      98.000000
max      99.000000
Name: marks, dtype: float64

### Block 3 — Selecting one column
- `df["col"]` selects one column and returns a Series; it always works.
- `df.col` is a shortcut that returns the same Series.
- The dot shortcut fails when the name has a space or matches a pandas method (e.g. count); use brackets then.
- Column names must match exactly, including capital letters and spaces.
- KeyError means no column has that exact name; check spelling, capitals and hidden spaces.
- Prefer brackets: they work for every column name.

Q1. Select the name column from students using brackets.

Q2. Select the city column using the dot way.

Q3. Combine with Topic 1: show only the first 5 values of the survey's Country column. (Load survey in this notebook first.)

Q4. Find the bug. Run this, read the last line, and fix it:

python
students["Name"]

Q5. Predict, then check: what do type(students["marks"]) and students["marks"].shape give?

Q6. Think. A table has a column called first name. Why does table.first name break? Which way works?

Q7. Real data. Run describe() on the survey's ConvertedComp (salary) column. What is the median salary?

In [27]:
students = pd.read_csv("students.csv")                                            # load the students table
survey = pd.read_csv("../data/raw/stackoverflow_2019/survey_results_public.csv")  # load the survey

# Q1: brackets (always works)
print("Q1:")
print(students["name"])                         # the name column as a Series

# Q2: dot shortcut (same result)
print("Q2:")
print(students.city)                            # the city column as a Series

# Q3: select the column first, then take its first 5 values
print("Q3:")
print(survey["Country"].head())                 # first 5 countries only

# Q4: fixed: was students["Name"] → KeyError: 'Name' (names must match exactly)
print("Q4:")
print(students["name"])                         # correct name is lowercase

# Q5: one column → Series; shape has one number (4 students)
print("Q5:", type(students["marks"]), students["marks"].shape)

# Q6 (think only, no code): "first name" has a space, so the dot way is broken code.
# Brackets work: table["first name"]

# Q7: select the salary column first, then describe it; the median is the 50% row
print("Q7:")
print(survey["ConvertedComp"].describe())       # summary of salary only

Q1:
0      Asha
1     Vivek
2      Ravi
3     Meena
4    Vinita
Name: name, dtype: object
Q2:
0    Indore
1      Pune
2     Delhi
3    Indore
4    Indore
Name: city, dtype: object
Q3:
0            United Kingdom
1    Bosnia and Herzegovina
2                  Thailand
3             United States
4                   Ukraine
Name: Country, dtype: object
Q4:
0      Asha
1     Vivek
2      Ravi
3     Meena
4    Vinita
Name: name, dtype: object
Q5: <class 'pandas.core.series.Series'> (5,)
Q7:
count    5.582300e+04
mean     1.271107e+05
std      2.841523e+05
min      0.000000e+00
25%      2.577750e+04
50%      5.728700e+04
75%      1.000000e+05
max      2.000000e+06
Name: ConvertedComp, dtype: float64

### Block 4 — Selecting many columns
- `df[["a", "b"]]` selects several columns: outer brackets = select, inner brackets = list of names.
- The result is a DataFrame, with columns in the order listed.
- The list can be stored in a variable first: `cols = ["a", "b"]`, then `df[cols]`.
- `df["a"]` gives a Series; `df[["a"]]` gives a one-column DataFrame.
- Forgetting the inner brackets (`df["a", "b"]`) raises a KeyError.
- In ML, the chosen input columns (features) are usually selected this way.

Practice (Block 4)

Guess first, then code. Easy to harder.

Q1. From students, select name and city together.

Q2. Select marks, name, city in that order.

Q3. Predict, then check: what do type(students[["marks"]]) and type(students["marks"]) give? Why are they different?

Q4. Find the bug. Run this, read the last line, and fix it:

python
students["name", "city"]

Q5. Real data. From survey, make a smaller table called small with only Country, Age, and ConvertedComp. Show its first 5 rows and its shape.

Q6. Combine. Run describe() on small. Which of its 3 columns appear, and why not all 3?

In [ ]:
x = students[["name","city"]]
print(x)

y = students[["marks","name", "city"]]
print(y)

#  double brackets → DataFrame; shape has two numbers (4 students, 1 column)
type(students[["marks"]]) 
# single bracket → Series
type(students["marks"]) 

# students["name", "city"]
# no columns available as exactly of same name

small = survey[["Country","Age", "ConvertedComp"]]
print(small.shape)
print(small.head(5))
small.describe()

     name    city
0    Asha  Indore
1   Vivek    Pune
2    Ravi   Delhi
3   Meena  Indore
4  Vinita  Indore
   marks    name    city
0     82    Asha  Indore
1     91   Vivek    Pune
2     67    Ravi   Delhi
3     75   Meena  Indore
4     95  Vinita  Indore
(88883, 3)
                  Country   Age  ConvertedComp
0          United Kingdom  14.0            NaN
1  Bosnia and Herzegovina  19.0            NaN
2                Thailand  28.0         8820.0
3           United States  22.0        61000.0
4                 Ukraine  30.0            NaN

                Age  ConvertedComp
count  79210.000000   5.582300e+04
mean      30.336699   1.271107e+05
std        9.178390   2.841523e+05
min        1.000000   0.000000e+00
25%       24.000000   2.577750e+04
50%       29.000000   5.728700e+04
75%       35.000000   1.000000e+05
max       99.000000   2.000000e+06

### Block 5 — The columns attribute
- `df.columns` lists every column name; it is an attribute, so no brackets.
- The result is an Index, pandas' list of labels; `list(df.columns)` turns it into a plain list.
- `len(df.columns)` counts the columns (same as the second number of `df.shape`).
- `"name" in df.columns` checks whether a column with exactly that name exists (True/False).
- Names are shown in quotes, which makes hidden spaces visible.
- Check `df.columns` first whenever a KeyError appears.

Practice (Block 5)

Guess first, then code. Use print() when there are several lines in one cell!

Q1. Load fruits.csv and show its columns. Is there a hidden space in any name?

Q2. How many columns does survey have? Use len, not shape.

Q3. Predict, then check: "Country" in survey.columns and "country" in survey.columns.

Q4. Find the bug. Run this, read the last line, and fix it:

python
students.columns()

Q5. Real data. Print list(survey.columns) and find the 3 column names that start with Years or end with 1stCode. Then select those 3 into a table called coding_years and show its first 5 rows.

Q6. Think. survey.shape gives (88883, 85). Which of those two numbers equals len(survey.columns), and why?

In [11]:
fruits = pd.read_csv("fruits.csv")
print(fruits.columns)
# first no () needed then Price is wrong we need to use "Price "
print(fruits["Price "])
print("Country" in survey.columns)
# no braces needed for columns, because it is not a method, it is an attribute of the DataFrame.
# 85 because shape show (row,columns)

print(list(survey.columns))                                    # step 1: read every column name

coding_years = survey[["YearsCode", "Age1stCode", "YearsCodePro"]]   # step 2: select the 3 exact names
print(coding_years.shape)                                      # check: 88883 rows, 3 columns
coding_years.head()                                            # last line, so shown as a neat table"

Index(['Fruit', 'Color', 'Price '], dtype='object')
0    180
1    200
2     50
3    110
Name: Price , dtype: int64
True
['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith', 'DatabaseDesireNextYear', 'PlatformWorkedWith', 'PlatformDesireNextYear', 'WebFrameWorkedWith', 'WebFrameDesireNextYear', 'MiscTechWorkedWith', 'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers', 'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn', 'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st', 'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved', 'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams', 'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans', 'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase']
(88883, 3)

  YearsCode Age1stCode      YearsCodePro
0         4         10               NaN
1       NaN         17               NaN
2         3         22                 1
3         3         16  Less than 1 year
4        16         14                 9

### Block 6 — iloc (selecting by position)
- `df.iloc[...]` selects by position number, counting from 0; it uses square brackets.
- `iloc[n]` returns one row as a Series (column names become its labels).
- `iloc[-1]` is the last row; negative positions count from the end.
- `iloc[[a, b]]` returns the listed rows as a DataFrame.
- `iloc[start:stop]` returns a range of rows; the stop position is not included.
- `iloc[row, col]` returns a single value; the row comes first, then the column.
- A position beyond the last row raises IndexError (out-of-bounds).

Practice (Block 6)

Guess first, then code. One question per cell, or use print().

Q1. Show the last row of students in two ways: with its position number, and with -1.

Q2. Show the rows at positions 1 and 3 together.

Q3. Show the first 3 rows with a slice. Which Topic 1 method gives the same result?

Q4. Predict, then check: what does students.iloc[0, 2] give?

Q5. Find the bug. Run this, read the last line, and explain:

python
students.iloc[4]

Q6. Find the bug. Run this. You won't get a row, just a strange line. Why, and what's the fix?

python
students.iloc(0)

Q7. Real data. Show the first respondent's full answers with survey.iloc[0]. Which country are they from? Then predict the shape of survey.iloc[0:3, 0:5] and check it.

In [15]:
# Q1: last row, two ways
print("Q1a:")
print(students.iloc[3])            # position 3 = the 4th and last row (positions 0, 1, 2, 3)
print("Q1b:")
print(students.iloc[-1])           # -1 counts from the end, so it's the last row

# Q2: rows at positions 1 and 3
print("Q2:")
print(students.iloc[[1, 3]])       # a list of positions inside, so a DataFrame comes back

# Q3: first 3 rows with a slice (same as students.head(3))
print("Q3:")
print(students.iloc[0:3])          # positions 0, 1, 2 (the stop, 3, is not included)

# Q4: a single cell (row first, then column)
print("Q4:", students.iloc[0, 2])  # row 0 = Asha, column 2 = marks, so 82

# Q5 (think): students.iloc[4] → IndexError: single positional indexer is out-of-bounds
# 4 rows means positions 0-3 only, so position 4 does not exist

# Q6 (think): students.iloc(0) uses round brackets, so you get a strange object, not a row
# Fix: students.iloc[0] (iloc always uses square brackets)

# Q7: real data
print("Q7a:")
print(survey.iloc[0])              # all answers of the first respondent (Country: United Kingdom)
print("Q7b:", survey.iloc[0:3, 0:5].shape)   # rows 0-2 and columns 0-4, so (3, 5)

Q1a:
name      Meena
city     Indore
marks        75
Name: 3, dtype: object
Q1b:
name     Vinita
city     Indore
marks        95
Name: 4, dtype: object
Q2:
    name    city  marks
1  Vivek    Pune     91
3  Meena  Indore     75
Q3:
    name    city  marks
0   Asha  Indore     82
1  Vivek    Pune     91
2   Ravi   Delhi     67
Q4: 82
Q7a:
Respondent                                                      1
MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 0, Length: 85, dtype: object
Q7b: (3, 5)

### Block 7 — loc (selecting by label)
- `df.loc[...]` selects by label: the row labels on the left and the column names.
- `loc[label]` returns one row; `loc[label, "col"]` returns one value.
- `loc[[a, b], ["col1", "col2"]]` returns chosen rows and chosen columns as a DataFrame.
- `loc[start:stop]` includes the stop label (unlike iloc, which excludes it).
- With the default index, labels equal positions; after filtering, sorting or tail(), they differ.
- A label that does not exist raises KeyError.
- iloc = positions and column numbers; loc = labels and column names.

Practice (Block 7)

Guess first, then code. One question per cell, or use print().

Q1. Show the row with label 1 using loc.

Q2. Show Vivek's city using loc, with a row label and a column name.

Q3. Predict, then check: how many rows does students.loc[1:3] give? And students.iloc[1:3]? Why different?

Q4. Show rows with labels 0 and 3, with only the name and marks columns.

Q5. Find the bug. Run this, read the last line, and fix it so it gives Asha's city:

python
students.loc[0, 1]

Q6. The trap. Run last_two = students.tail(2), then last_two.loc[0]. Why the KeyError? Write two different lines that give Ravi's row instead.

Q7. Real data. Show survey.loc[0, "Country"]. Then predict the shape of survey.loc[0:4, ["Country", "Age"]] and check it.

In [24]:
print(students.loc[0, "name"])
print(students.loc[3, "city"])
print(students.loc[1:3])
print(students.iloc[1:3])
print(students.loc[[1,3],["name", "marks"]])
print(students.loc[[0, 1],["city"]])

Asha
Indore
    name    city  marks
1  Vivek    Pune     91
2   Ravi   Delhi     67
3  Meena  Indore     75
    name   city  marks
1  Vivek   Pune     91
2   Ravi  Delhi     67
    name  marks
1  Vivek     91
3  Meena     75
     city
0  Indore
1    Pune

### value_counts()

- Counts how many times each value appears in ONE column (a tally chart)
- Call it on a Series: `df["col"].value_counts()`
- Result is a Series, sorted from biggest count to smallest
- `normalize=True` gives shares (0 to 1); multiply by 100 for percentages
- `dropna=False` also counts missing values (NaN); by default they are hidden
- Argument names a column, not a value inside the column
- Can be chained: `.head(n)` for top n rows, `.index[0]` for the top value's name

Write code to count how many students live in each city.

In [10]:
student = pd.read_csv("students.csv")
print(student["city"].value_counts())
print(student["city"].value_counts(normalize=True))
print((student["city"].value_counts(normalize=True))*100)

print(student.value_counts(dropna=False))   # dropna=False keeps NaN in the count

city
Indore    3
Pune      1
Delhi     1
Name: count, dtype: int64
city
Indore    0.6
Pune      0.2
Delhi     0.2
Name: proportion, dtype: float64
city
Indore    60.0
Pune      20.0
Delhi     20.0
Name: proportion, dtype: float64
name    city    marks
Asha    Indore  82       1
Meena   Indore  75       1
Ravi    Delhi   67       1
Vinita  Indore  95       1
Vivek   Pune    91       1
Name: count, dtype: int64

### dtypes

- dtype = the kind of data a column holds; one column has one dtype
- `df.dtypes` shows every column's type (attribute, no brackets); `df["col"].dtype` shows one
- `int64` whole numbers, `float64` decimals, `object` text, `bool` True/False
- What you can do with a column depends on its dtype (add numbers, not text)
- One text cell in a numeric column turns the whole column into `object`
- A column with NaN is stored as `float64`
- `info()` also lists each column's dtype

Q1. Why is qty object and not int64?
One cell in the column is the text "five" (the Bottle row). A column holds only one dtype, and numbers and text cannot share int64. So pandas stores the whole column as object. The other numbers (50, 20, 12, 3, 1) are no longer treated as numbers either, so you cannot add or average them until the bad cell is fixed.

Q2. Why is rating float64?
Two cells in the column are empty (Notebook and Lamp), and pandas stores an empty cell as NaN. NaN is a decimal (float) value, and a whole column cannot be int64 while holding it. The other values are converted to decimals too. So the column is float64 because of the NaN, not because of the 4.5.